name: builds

on:
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Configure
        run: |
          - cd OpenDUNE && ./configure --prefix-dir=${HOME} --without-sdl &&  make -j3 && make bundle_zip