name: builds

on:
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        sdl: [ 1, 2 ]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies (Linux)
        run: sudo apt-get install gcc-mingw-w64-i686 dos2unix libsdl1.2-dev libsdl-image1.2-dev libsdl2-dev libsdl2-image-dev zip
        if: ${{ matrix.os == 'ubuntu-latest'}}
      - name: Update brew (MacOS)
        run: brew update
        if: ${{ matrix.os == 'macos-latest'}}
      - name: Install dependencies (MacOS)
        run: brew install sdl sdl_image
        if: ${{ matrix.os == 'macos-latest' && matrix.sdl == 1 }}
      - name: Install dependencies (MacOS)
        run: brew install sdl2 sdl2_image
        if: ${{ matrix.os == 'macos-latest' && matrix.sdl == 2 }}
      - name: Configure
        run: ./configure --prefix-dir=${HOME}
        if: ${{ matrix.sdl == 2}}
      - name: Configure
        run: ./configure --prefix-dir=${HOME} --without-sdl2
        if: ${{ matrix.sdl == 1}}
      - name: Compile
        run: make -j3
      - name: Bundle
        run: make bundle_zip
        if: ${{ matrix.os == 'ubuntu-latest'}}
      - name: Bundle
        run: make bundle_dmg
        if: ${{ matrix.os == 'macos-latest'}}
      - uses: actions/upload-artifact@v2
        with:
          name: MacOS build SDL${{ matrix.sdl }}
          path: bundles/*dmg
        if: ${{ matrix.os == 'macos-latest'}}
      - uses: actions/upload-artifact@v2
        with:
          name: Linux build SDL${{ matrix.sdl }}
          path: bundles/*zip
        if: ${{ matrix.os == 'ubuntu-latest'}}